import styles from '@/styles/Home.module.css'
import Head from 'next/head'
import * as React from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div data-testid="thisIsATest">This is a test</div>
        <div data-testid="testing">Testing</div>
      </main>
    </>
  )
}
