import styles from '@/styles/Home.module.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const handleClickSignOut = () => {
    localStorage.setItem('loggedIn', 'false');
    const channel = new BroadcastChannel('logout');
    channel.postMessage('user logged out');
  }

  const handleClickSignIn = () => {
    localStorage.setItem('loggedIn', 'true');
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <button onClick={handleClickSignIn}> Login</button>
        <button onClick={handleClickSignOut}> Logout</button>
      </main>
    </>
  )
}
