import Head from 'next/head'
import React from 'react'
import styles from '../../styles/Home.module.css'
interface LayoutProps {
    children?: any
}
const Layout: React.FC<LayoutProps> = ({ children }) => {
    return (<>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            {children}
        </main>
    </>
    )
}

export default Layout